package org.hildan.accounting.mortgage

import kotlinx.datetime.*
import org.hildan.accounting.money.*

/**
 * A payment towards the mortgage.
 */
data class MortgagePayment(
    /**
     * The date this payment was made.
     */
    val date: LocalDate,
    /**
     * The balance of the mortgage before making this payment.
     */
    val balanceBefore: Amount,
    /**
     * The balance of the construction account at the start of the month.
     */
    val constructionAccountBalanceBefore: Amount,
    /**
     * The amount used to pay back the mortgage, which is subtracted from the current mortgage balance as a result.
     */
    val principalReduction: Amount,
    /**
     * The amount invested voluntarily to repay a part of the mortgage this month on top of the mandatory payment.
     * Like [principalReduction], it is subtracted from the current mortgage balance (principal) as a result.
     */
    val extraPrincipalReduction: Amount,
    /**
     * The applicable annual interest rate at the time of this payment.
     */
    val appliedInterestRate: Fraction,
    /**
     * The interest paid to the bank for borrowing the money.
     */
    val interest: Amount,
    /**
     * The interest generated by the construction account for this month, and which should be deducted from the
     * effective monthly payment to the bank the next month.
     */
    val constructionAccountGeneratedInterest: Amount,
    /**
     * The interest generated by the construction account in the previous month, and which should be deducted from the
     * effective monthly payment to the bank for this month.
     */
    val constructionAccountDeductedInterest: Amount,
) {
    /**
     * The total amount paid to the bank.
     */
    val total: Amount = principalReduction + extraPrincipalReduction + interest - constructionAccountDeductedInterest
}
